# Generated by Django 5.2 on 2025-04-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('difficulty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('multiplier', models.FloatField(default=1.0)),
                ('board_rows', models.PositiveSmallIntegerField(default=4)),
                ('board_cols', models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                'verbose_name_plural': 'difficulties',
                'db_table': 'difficulties',
            },
        ),
        migrations.CreateModel(
            name='CardPair',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_a', models.CharField(max_length=255)),
                ('card_b', models.CharField(max_length=255)),
                ('pair_type', models.CharField(choices=[('letter-image', 'Letra con Imagen'), ('word-definition', 'Palabra con Definición'), ('word-image', 'Palabra con Imagen'), ('synonym-antonym', 'Sinónimo/Antónimo')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.difficulty')),
            ],
            options={
                'db_table': 'card_pairs',
                'unique_together': {('card_a', 'card_b', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.difficulty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('move_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_match', models.BooleanField()),
                ('move_time', models.DateTimeField(auto_now_add=True)),
                ('card_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_a_moves', to='game.cardpair')),
                ('card_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_b_moves', to='game.cardpair')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'db_table': 'moves',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('mismatches', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
