# Generated by Django 5.2 on 2025-04-09 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpair',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='difficulty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.RemoveField(
            model_name='move',
            name='id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='cardpair',
            name='pair_id',
            field=models.AutoField(db_column='pair_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.AutoField(db_column='category_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='difficulty_id',
            field=models.AutoField(db_column='difficulty_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.AutoField(db_column='game_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='move',
            name='move_id',
            field=models.AutoField(db_column='move_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='score',
            name='score_id',
            field=models.AutoField(db_column='score_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cardpair',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.category'),
        ),
        migrations.AlterField(
            model_name='cardpair',
            name='difficulty',
            field=models.ForeignKey(db_column='difficulty_id', on_delete=django.db.models.deletion.CASCADE, to='game.difficulty'),
        ),
        migrations.AlterField(
            model_name='game',
            name='completed',
            field=models.BooleanField(db_column='completed', default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.ForeignKey(db_column='difficulty_id', on_delete=django.db.models.deletion.CASCADE, to='game.difficulty'),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, db_column='end_time', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_column='start_time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='move',
            name='card_a',
            field=models.ForeignKey(db_column='card_a_id', on_delete=django.db.models.deletion.CASCADE, related_name='card_a_moves', to='game.cardpair'),
        ),
        migrations.AlterField(
            model_name='move',
            name='card_b',
            field=models.ForeignKey(db_column='card_b_id', on_delete=django.db.models.deletion.CASCADE, related_name='card_b_moves', to='game.cardpair'),
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='is_match',
            field=models.BooleanField(db_column='is_match'),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_time',
            field=models.DateTimeField(auto_now_add=True, db_column='move_time'),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='score',
            name='matches',
            field=models.IntegerField(db_column='matches'),
        ),
        migrations.AlterField(
            model_name='score',
            name='mismatches',
            field=models.IntegerField(db_column='mismatches'),
        ),
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.IntegerField(db_column='points'),
        ),
        migrations.AlterField(
            model_name='score',
            name='time_taken',
            field=models.IntegerField(db_column='time_taken'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
